version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: jenkins_mongodb
    ports:
      - "27018:27017"          # Different port for CI/CD
    volumes:
      - mongo-data-ci:/data/db

  app:
    build: .                  # Build from local code volume
    container_name: jenkins_nodeapp
    ports:
      - "3001:3000"           # Different port for CI/CD
    volumes:
      - ./src:/usr/src/app    # Code volume
    environment:
      - MONGO_URL=mongodb:27017/hustleBust
    depends_on:
      - mongodb

volumes:
  mongo-data-ci:
